// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYSUuarisPBwn5lRmIbaZiXPzV7I2HvYw',
    appId: '1:872976874500:web:981abe82bf3679cd578951',
    messagingSenderId: '872976874500',
    projectId: 'database-skripsi-c6759',
    authDomain: 'database-skripsi-c6759.firebaseapp.com',
    storageBucket: 'database-skripsi-c6759.appspot.com',
    measurementId: 'G-D8TLETRV1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT04jfuuX0jL6W_x1dwW23AUu3wfvrDjE',
    appId: '1:872976874500:android:18e52f4a7e20dd44578951',
    messagingSenderId: '872976874500',
    projectId: 'database-skripsi-c6759',
    storageBucket: 'database-skripsi-c6759.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7LXQWwoBOgej3UQmTDpUKOaS4wiQVLXA',
    appId: '1:872976874500:ios:62c33e107377f049578951',
    messagingSenderId: '872976874500',
    projectId: 'database-skripsi-c6759',
    storageBucket: 'database-skripsi-c6759.appspot.com',
    iosBundleId: 'com.example.molPetani',
  );
}
